parameters:
    system_option.model_manager: ~
    system_option.manager.class: SmileSRG\SystemOptionBundle\Manager\SystemOptionManager

services:
    system_option.manager:
        class: SmileSRG\SystemOptionBundle\Manager\SystemOptionManager
        arguments: [%system_option.model_manager%, @logger]
        tags:
            - { name: monolog.logger, channel: system_option }

    twig.system_option_extension:
        class: %system_option.manager.class%
        arguments: [@system_option.manager]
        tags:
            - { name: twig.extension }
